my_string= input('Введите свой текст: ')
print('Количество символов введеного слова: ', len(my_string))
print('Верхний регистр: ', my_string .upper())
print('Нижний регистр: ', my_string .lower())
print('Без пробелов: ', my_string .replace(' ', ''))
print('Первый символ: ', my_string[0])
print('Последний символ: ', my_string[-1])